name: main

on:
  pull_request:
  push:
    branches: main

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          "ubuntu-latest",
          "macos-latest",
          "windows-latest",
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: clippy, rustfmt
      - run: cargo install cargo-all-features
      - run: cargo check-all-features

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          "ubuntu-latest",
          "macos-latest",
          "windows-latest",
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
      - run: cargo install cargo-all-features
      - run: cargo test-all-features
